### ISSUE TITLE
Create a Blog card for the Blog page

### ISSUE THREAD

**Issue by osujipius** [osujipius/workaholic#12]
Make blog cards similar to the one for https://findmycar.netlify.app and link it to related stories and images about jobs.

**Comment by okerekechinweotito** [comment]
@OsujiPius  provide a more detailed explanation for this issue

**Comment by osujipius** [comment]
What don't you seem to understand. Create replica blog cards of the ones found in the above mentioned site. With links to job related stories and images to correspond
