### ISSUE TITLE
Fixed page not found error when trying to navigate back to a previous page

### ISSUE THREAD

**Issue by osujipius** [osujipius/workaholic#19]
![Screenshot (121)](https://user-images.githubusercontent.com/94569961/193873627-065e94ff-fa2b-4ea0-8592-25200462087d.png)

**Comment by okerekechinweotito** [comment]
@OsujiPius
I could not recreate this bug on my local 
give detailed explanation on how to recreate bug

**Comment by osujipius** [comment]
Sign In and on redirection. You will experience the bug @okerekechinweotito

**Comment by okerekechinweotito** [comment]
@OsujiPius 
Is continuous integration enabled on this site ?
Kindly retrigger deploy

**Comment by okerekechinweotito** [comment]
@OsujiPius 
I have fixed the issue , you can close the issue now.

**Comment by okerekechinweotito** [comment]
@OsujiPius 
As a side note ;
Respectfully sir , read documentation and conduct proper research before injecting a new technology to your codebase.
Do not make it a habit of pushing beans code to this repository.

 Warm Regards
