### ISSUE TITLE
Create a job card component

### ISSUE THREAD

**Issue by osujipius** [osujipius/workaholic#21]
Create a job card component that will carry the position title, company name, description about the position, skills needed for the position and a button to apply. Don't wait for design!!! Use your creativity

**Comment by osujipius** [comment]
![Screenshot (123)](https://user-images.githubusercontent.com/94569961/194032188-77ec3d31-8cac-4d31-ab47-8170a8a994b9.png)

Use this as reference @okerekechinweotito

**Comment by okerekechinweotito** [comment]
@OsujiPius 
This reference needs revision

**Comment by osujipius** [comment]
@okerekechinweotito what is unclear to you about the reference?
Make a responsive card like that... That will have the job position title, description and skills like seen in the reference and a CTA to apply

**Comment by osujipius** [comment]
@okerekechinweotito 
![Screenshot_20221008-141314](https://user-images.githubusercontent.com/94569961/194709387-24bfbbf1-3aa4-4a5c-8298-d368f20c244d.jpg)
